config/routes.rb
Rails.application.routes.draw do
  get 'labs/lab3'

  get 'labs/lab4'

  get 'labs/index'
  
  root "labs#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/lab3_controller.rb
class Lab3Controller < ApplicationController
end

app/controllers/lab4_controller.rb
class Lab4Controller < ApplicationController
end

app/controllers/labs_controller.rb
class LabsController < ApplicationController
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/hello_helper.rb
module HelloHelper
end

app/helpers/index_helper.rb
module IndexHelper
end

app/helpers/lab3_helper.rb
module Lab3Helper
end

app/views/labs/index.html.erb
<ul class="switch-pages">
    <li><a class="switch-pages-item" href="<%= labs_lab3_path(@lab3)%>">lab3</a></li>
</ul>

<h1>hello</h1>

app/views/labs/lab3.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="./assets/stylessheet/application.css">
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Manrope:wght@400;700&display=swap" rel="stylesheet">
    <title>Resume</title>
</head>
<body>
    <ul class="switch-pages">
        <li><a class="switch-pages-item" href="<%= labs_index_path(@index)%>">lab1</a></li>
        <li><a class="switch-pages-item" href="<%= labs_lab4_path(@lab4)%>">lab4</a></li>
    </ul>
    
    <%# заголовок лабораторної %>
    <p class="lab-header">Ничик Богдан, група ІП-20-1, варіант:??</p>
    <p class="lab-number">Лабораторна робота №3</p>
    <p class="lab-theme">тема: "HTML, CSS. Використання таблиць та стилів"</p>
    
    <%# резюме %>
    <table>
        <caption>Resume</caption>
        <thead>
            <tr>
                <th>Element</th>
                <th>Description</th>
            </tr>
        </thead>
        
        <tbody>
            <tr>
                <td>Name</td>
                <td>Bohdan Nychyk</td>
            </tr>
            
            <tr>
                <td>Email</td>
                <td>nychyk.b@gmail.com</td>
            </tr>
            
            <tr>
                <td>Phone number</td>
                <td>+380686808321</td>
            </tr>

            <tr>
                <td>Residence</td>
                <td>Ivano-Frankivsk</td>
            </tr>

            <tr>
                <td>Links</td>
                <td>linkedin.com</td>
            </tr>

            <tr>
                <td>Profile</td>
                <td>Dolore dolore sit sit esse sunt labore adipisicing Lorem reprehenderit. Anim magna qui veniam adipisicing duis eu ex occaecat. Dolor reprehenderit aliquip magna non ut ut.</td>
            </tr>

            <tr>
                <td>Technical skills</td>
                <td>
                    <ul>
                        <li>Ex elit excepteur occaecat non labore</li>
                        <li>Ex elit excepteur occaecat non labore</li>
                        <li>Ex elit excepteur occaecat non labore</li>
                        <li>Ex elit excepteur occaecat non labore</li>
                        <li>Ex elit excepteur occaecat non labore </li>
                        <li>Ex elit excepteur occaecat non labore</li>
                    </ul>
                </td>
            </tr>

            <tr>
                <td>Tools</td>
                <td>
                    <ul>
                        <li>Ex elit excepteur occaecat non labore</li>
                        <li>Ex elit excepteur occaecat non labore</li>
                        <li>Ex elit excepteur occaecat non labore</li>
                        <li>Ex elit excepteur occaecat non labore</li>
                        <li>Ex elit excepteur occaecat non labore</li>
                    </ul>
                </td>
            </tr>

            <tr>
                <td>Education</td>
                <td>IVANO-FRANKIVSK NATIONAL TECHICAL UNIVERSITY OF OIL AND GAS</td>
            </tr>

            <tr>
                <td>Experience</td>
                <td>Dolore dolore sit sit esse sunt labore adipisicing Lorem reprehenderit. Anim magna qui veniam adipisicing duis eu ex occaecat. Dolor reprehenderit aliquip magna non ut ut.</td>
            </tr>

            <tr>
                <td>Languages</td>
                <td>English (Intermediate)</td>
            </tr>
        </tbody>
        
    </table>

    
</body>

app/views/labs/lab4.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    
    <%# bnygv43ntuh9bnp %>
 
    <title>Resume</title>
</head>
<body>
    <ul class="switch-pages">
        <li><a class="switch-pages-item" href="<%= labs_lab3_path(@lab3)%>">lab3</a></li>
    </ul>

    <%# заголовок лабораторної %>
    <div class="lab-info">
        <p class="lab-header">Ничик Богдан, група ІП-20-1, варіант:??</p>
        <p class="lab-number">Лабораторна робота №4</p>
        <p class="lab-theme">тема: "HTML, CSS. Бібліотеки та фреймворки"</p>
    </div>

    

    <%# резюме %>
    <table class="table table-sm">
            <caption class="table caption-top">Resume</caption>
            <thead class="table-head">
                <tr class="bg-warning">
                    <th>Element</th>
                    <th>Description</th>
                </tr>
            </thead>
            
            <tbody class="table-body">
                <tr class="table-content">
                    <td class="element">Name</td>
                    <td class="value">Bohdan Nychyk</td>
                </tr>
                
                <tr class="table-content">
                    <td class="element">Email</td>
                    <td class="value">nychyk.b@gmail.com</td>
                </tr>
                
                <tr class="table-content">
                    <td class="element">Phone number</td>
                    <td class="value">+380686808321</td>
                </tr>

                <tr class="table-content">
                    <td class="element">Residence</td>
                    <td class="value">Ivano-Frankivsk</td>
                </tr>

                <tr class="table-content">
                    <td class="element">Links</td>
                    <td class="value">linkedin.com</td>
                </tr>

                <tr class="table-content">
                    <td class="element">Profile</td>
                    <td class="value">Dolore dolore sit sit esse sunt labore adipisicing Lorem reprehenderit. Anim magna qui veniam adipisicing duis eu ex occaecat. Dolor reprehenderit aliquip magna non ut ut.</td>
                </tr>

                <tr class="table-content">
                    <td class="element">Technical skills</td>
                    <td class="value">
                        <ul>
                            <li>Ex elit excepteur occaecat non labore</li>
                            <li>Ex elit excepteur occaecat non labore</li>
                            <li>Ex elit excepteur occaecat non labore</li>
                            <li>Ex elit excepteur occaecat non labore</li>
                            <li>Ex elit excepteur occaecat non labore </li>
                            <li>Ex elit excepteur occaecat non labore</li>
                        </ul>
                    </td>
                </tr>

                <tr class="table-content">
                    <td class="element">Tools</td>
                    <td class="value">
                        <ul>
                            <li>Ex elit excepteur occaecat non labore</li>
                            <li>Ex elit excepteur occaecat non labore</li>
                            <li>Ex elit excepteur occaecat non labore</li>
                            <li>Ex elit excepteur occaecat non labore</li>
                            <li>Ex elit excepteur occaecat non labore</li>
                        </ul>
                    </td>
                </tr>

                <tr class="table-content">
                    <td class="element">Education</td>
                    <td class="value">IVANO-FRANKIVSK NATIONAL TECHICAL UNIVERSITY OF OIL AND GAS</td>
                </tr>

                <tr class="table-content">
                    <td class="element">Experience</td>
                    <td class="value">Dolore dolore sit sit esse sunt labore adipisicing Lorem reprehenderit. Anim magna qui veniam adipisicing duis eu ex occaecat. Dolor reprehenderit aliquip magna non ut ut.</td>
                </tr>

                <tr class="table-content">
                    <td class="element">Languages</td>
                    <td class="value">English (Intermediate)</td>
                </tr>
            </tbody>
            
        </table>
    
</body>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Labs</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <!-- Latest compiled and minified CSS -->
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@3.3.7/dist/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">

    <!-- Optional theme -->
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@3.3.7/dist/css/bootstrap-theme.min.css" integrity="sha384-rHyoN1iRsVXV4nD0JutlnGaslCJuC7uwjduW9SVrLvRYooPp2bWYgmgJQIXwl/Sp" crossorigin="anonymous">

    <!-- Latest compiled and minified JavaScript -->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@3.3.7/dist/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>